kind: pipeline
type: docker
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
  - name: test
    image: golang
    detach: true
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

#  - name: build
#    image: golang
#    volumes:
#      - name: deps
#        path: /go
#    commands:
#      - go build
#    when:
#        event:
#            - tag

  - name: build-docker
    image: plugins/docker
    settings:
      registry: git.frytea.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: git.frytea.com/songtianlun/bj-pfd2
      tags:
        - ${DRONE_TAG}
        - latest
      dockerfile: Dockerfile
      insecure: true
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/release-*

volumes:
  - name: deps
    temp: {}


trigger:
  ref:
    - refs/tags/*
    - refs/heads/*
