kind: pipeline
type: docker
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
  - name: test
    image: golang
    detach: true
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

#  - name: build
#    image: golang
#    volumes:
#      - name: deps
#        path: /go
#    commands:
#      - go build
#    when:
#        event:
#            - tag

  - name: build-docker
    image: plugins/docker
    settings:
      registry: git.frytea.local:80
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: git.frytea.local:80/songtianlun/bj-pfd2
      tags:
        - ${DRONE_TAG}
        - latest
      dockerfile: Dockerfile
      insecure: true
    when:
      event:
        - tag
      ref:
        include:
          - refs/tags/release-*
  - name: deploy to k8s
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server:
        from_secret: K8S_SERVER
      kubernetes_token:
        from_secret: K8S_TOKEN
      kubernetes_cert:
        from_secret: K8S_CERT
      namespace: bjpfd2-frytea
      deployment: bjpfd2-frytea-app
      container: bjpfd2-backend
      repo: git.frytea.local:80/songtianlun/bj-pfd2
      tag: ${DRONE_TAG}

    when:
      event:
        - tag

volumes:
  - name: deps
    temp: {}


trigger:
  ref:
    - refs/tags/*
    - refs/heads/*