kind: pipeline
name: default

clone:
  depth: 50
  tags: true
  skip_verify: true

steps:
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go build

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
    - drone
  event:
    - push